// Copyright 2026 RSE Candidate
// Licensed under the Apache License, Version 2.0.

#include "amr_navigation/slope_cost_model.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace amr_navigation
{

namespace
{

/// \brief Minimal PGM (P5, 8-bit binary) reader.
///
/// Deliberately hand-rolled rather than pulling in an image library: the
/// format is a dozen lines, and this avoids making the navigation stack depend
/// on OpenCV purely to read a height field.
std::vector<std::uint8_t> ReadPgm(
  const std::string & path, std::uint32_t * width, std::uint32_t * height)
{
  std::ifstream file(path, std::ios::binary);
  if (!file) {
    throw std::runtime_error("cannot open elevation image '" + path + "'");
  }

  std::string magic;
  file >> magic;
  if (magic != "P5") {
    throw std::runtime_error(
            "elevation image '" + path + "' is '" + magic + "', expected binary PGM (P5)");
  }

  // PGM allows comments anywhere in the header.
  auto read_value = [&file]() {
      int value = 0;
      while (file >> std::ws, file.peek() == '#') {
        std::string comment;
        std::getline(file, comment);
      }
      file >> value;
      return value;
    };

  const int parsed_width = read_value();
  const int parsed_height = read_value();
  const int max_value = read_value();
  if (parsed_width <= 0 || parsed_height <= 0 || max_value != 255) {
    throw std::runtime_error("elevation image '" + path + "' has an unsupported header");
  }
  file.get();   // Consume the single whitespace byte before the raster.

  const std::size_t count =
    static_cast<std::size_t>(parsed_width) * static_cast<std::size_t>(parsed_height);
  std::vector<std::uint8_t> pixels(count);
  file.read(reinterpret_cast<char *>(pixels.data()), static_cast<std::streamsize>(count));
  if (static_cast<std::size_t>(file.gcount()) != count) {
    throw std::runtime_error(
            "elevation image '" + path + "' is truncated: expected " + std::to_string(count) +
            " bytes, got " + std::to_string(file.gcount()));
  }

  *width = static_cast<std::uint32_t>(parsed_width);
  *height = static_cast<std::uint32_t>(parsed_height);
  return pixels;
}

/// \brief Pull `key: value` out of a flat YAML file.
///
/// The metadata file is generated by this project and has a fixed, flat shape,
/// so a line scan is sufficient and keeps yaml-cpp out of the costmap plugin's
/// link line.
bool ReadScalar(const std::string & path, const std::string & key, std::string * value)
{
  std::ifstream file(path);
  if (!file) {
    return false;
  }
  std::string line;
  while (std::getline(file, line)) {
    const std::size_t comment = line.find('#');
    if (comment != std::string::npos) {
      line = line.substr(0, comment);
    }
    const std::size_t colon = line.find(':');
    if (colon == std::string::npos) {
      continue;
    }
    std::string found = line.substr(0, colon);
    found.erase(0, found.find_first_not_of(" \t"));
    found.erase(found.find_last_not_of(" \t") + 1);
    if (found != key) {
      continue;
    }
    std::string rest = line.substr(colon + 1);
    rest.erase(0, rest.find_first_not_of(" \t"));
    rest.erase(rest.find_last_not_of(" \t\r") + 1);
    *value = rest;
    return true;
  }
  return false;
}

double ReadRequiredDouble(const std::string & path, const std::string & key)
{
  std::string text;
  if (!ReadScalar(path, key, &text)) {
    throw std::runtime_error("elevation metadata '" + path + "' has no '" + key + "'");
  }
  return std::stod(text);
}

}  // namespace

// ---------------------------------------------------------------------------
// ElevationMap
// ---------------------------------------------------------------------------

double ElevationMap::HeightAt(double x, double y, double fallback) const
{
  if (Empty() || resolution <= 0.0) {
    return fallback;
  }
  const int column = static_cast<int>(std::floor((x - origin_x) / resolution));
  // Row 0 is maximum y, so the row index counts down from the top edge.
  const double y_max = origin_y + static_cast<double>(height) * resolution;
  const int row = static_cast<int>(std::floor((y_max - y) / resolution));

  if (column < 0 || row < 0 || column >= static_cast<int>(width) ||
    row >= static_cast<int>(height))
  {
    return fallback;
  }
  return heights[Index(static_cast<std::uint32_t>(column), static_cast<std::uint32_t>(row))];
}

bool ElevationMap::CellCentre(double x, double y, double * centre_x, double * centre_y) const
{
  if (Empty() || resolution <= 0.0) {
    return false;
  }
  const int column = static_cast<int>(std::floor((x - origin_x) / resolution));
  const double y_max = origin_y + static_cast<double>(height) * resolution;
  const int row = static_cast<int>(std::floor((y_max - y) / resolution));

  if (column < 0 || row < 0 || column >= static_cast<int>(width) ||
    row >= static_cast<int>(height))
  {
    return false;
  }
  *centre_x = origin_x + (static_cast<double>(column) + 0.5) * resolution;
  *centre_y = y_max - (static_cast<double>(row) + 0.5) * resolution;
  return true;
}

ElevationMap ElevationMap::FromFiles(const std::string & yaml_path)
{
  std::string image_name;
  if (!ReadScalar(yaml_path, "image", &image_name)) {
    throw std::runtime_error("elevation metadata '" + yaml_path + "' has no 'image'");
  }

  // Resolve the image relative to the metadata file.
  std::string image_path = image_name;
  if (!image_name.empty() && image_name.front() != '/') {
    const std::size_t slash = yaml_path.find_last_of('/');
    if (slash != std::string::npos) {
      image_path = yaml_path.substr(0, slash + 1) + image_name;
    }
  }

  ElevationMap map;
  map.resolution = ReadRequiredDouble(yaml_path, "resolution");
  const double elevation_min = ReadRequiredDouble(yaml_path, "elevation_min");
  const double elevation_max = ReadRequiredDouble(yaml_path, "elevation_max");

  std::string origin_text;
  if (!ReadScalar(yaml_path, "origin", &origin_text)) {
    throw std::runtime_error("elevation metadata '" + yaml_path + "' has no 'origin'");
  }
  // origin: [x, y, yaw]
  std::replace(origin_text.begin(), origin_text.end(), '[', ' ');
  std::replace(origin_text.begin(), origin_text.end(), ']', ' ');
  std::replace(origin_text.begin(), origin_text.end(), ',', ' ');
  std::istringstream origin_stream(origin_text);
  origin_stream >> map.origin_x >> map.origin_y;

  const std::vector<std::uint8_t> pixels = ReadPgm(image_path, &map.width, &map.height);
  const double span = elevation_max - elevation_min;
  map.heights.resize(pixels.size());
  for (std::size_t i = 0; i < pixels.size(); ++i) {
    map.heights[i] = elevation_min + static_cast<double>(pixels[i]) * span / 255.0;
  }
  return map;
}

// ---------------------------------------------------------------------------
// SlopeCostModel
// ---------------------------------------------------------------------------

SlopeCostModel::SlopeCostModel(const Options & options)
: options_(options) {}

SlopeSample SlopeCostModel::SampleSlope(const ElevationMap & map, double x, double y) const
{
  SlopeSample sample;
  if (map.Empty()) {
    return sample;
  }

  // Difference from the containing cell's centre, not from the raw query
  // point. Probing `x + resolution` from an arbitrary x is unsafe in floating
  // point: when x sits near a cell boundary the probe can round back into the
  // same cell, the stencil collapses from two cells to one, and the measured
  // gradient comes out at half its true value. That failure is silent, and it
  // under-reports exactly the steep slopes the lethal threshold exists to
  // catch. From a cell centre, +/- one resolution always lands in the
  // neighbouring cell.
  double sample_x = x;
  double sample_y = y;
  if (!map.CellCentre(x, y, &sample_x, &sample_y)) {
    return sample;   // Outside the map; caller applies the unknown policy.
  }

  const double step = map.resolution;
  const double centre = map.HeightAt(sample_x, sample_y);

  // Central differences. A forward difference would bias the computed slope
  // half a cell downhill and move the lethal boundary of a steep ramp by a
  // couple of centimetres.
  const double dz_dx =
    (map.HeightAt(sample_x + step, sample_y, centre) -
    map.HeightAt(sample_x - step, sample_y, centre)) / (2.0 * step);
  const double dz_dy =
    (map.HeightAt(sample_x, sample_y + step, centre) -
    map.HeightAt(sample_x, sample_y - step, centre)) / (2.0 * step);

  sample.gradient = std::hypot(dz_dx, dz_dy);
  sample.angle = std::atan(sample.gradient);
  sample.valid = true;
  return sample;
}

std::uint8_t SlopeCostModel::CostForAngle(double angle) const
{
  const double magnitude = std::abs(angle);

  if (magnitude <= options_.free_angle) {
    return kFree;
  }
  if (magnitude >= options_.max_traversable_angle) {
    // Beyond what the drive train can climb. Not expensive: impassable.
    return kLethal;
  }

  const double span = options_.max_traversable_angle - options_.free_angle;
  if (span <= 1e-9) {
    return kLethal;
  }
  const double fraction = (magnitude - options_.free_angle) / span;
  const double shaped = std::pow(std::min(1.0, std::max(0.0, fraction)), options_.curve_exponent);

  const double base = static_cast<double>(options_.base_cost);
  const double top = static_cast<double>(options_.max_cost);
  const double cost = base + (top - base) * shaped;

  // Clamp below LETHAL. A traversable slope priced at 254 would be refused
  // outright rather than merely avoided, which breaks the "ramps are used when
  // they are the only viable path" half of the requirement.
  return static_cast<std::uint8_t>(
    std::min(static_cast<double>(kLethal - 1), std::max(0.0, cost)));
}

std::uint8_t SlopeCostModel::CostAt(const ElevationMap & map, double x, double y) const
{
  const SlopeSample sample = SampleSlope(map, x, y);
  if (!sample.valid) {
    return options_.unknown_is_free ? kFree : kNoInformation;
  }
  return CostForAngle(sample.angle);
}

}  // namespace amr_navigation
